-- AuditMind document type master seed.
-- Keep names as exact requestable Korean document names. Do not use "등" in document type names.

WITH category_seed(code, name, description, sort_order) AS (
  VALUES
    ('company_basic', '회사 기본자료', '회사 실체, 지배구조, 내부규정 확인 자료', 10),
    ('accounting_closing', '회계장부 및 결산자료', '장부, 결산, 재무제표, 세무조정 관련 자료', 20),
    ('revenue', '매출자료', '매출 발생, 청구, 수금, 매출채권 관련 자료', 30),
    ('purchase_expense', '매입 및 비용자료', '매입, 비용, 적격증빙, 지출승인 관련 자료', 40),
    ('finance_cash', '금융 및 자금자료', '예금, 차입금, 담보, 보증, 자금흐름 관련 자료', 50),
    ('receivable_payable', '채권 및 채무자료', '채권채무 잔액, 조회, 장기 미회수 관련 자료', 60),
    ('inventory', '재고자료', '재고 수량, 수불, 실사, 평가 관련 자료', 70),
    ('fixed_intangible_assets', '유형자산 및 무형자산자료', '유형자산, 무형자산, 감가상각, 권리 관련 자료', 80),
    ('payroll_withholding', '인사·급여·원천세자료', '임직원, 급여, 원천세, 4대보험, 주식보상 관련 자료', 90),
    ('vat', '부가가치세자료', '부가가치세 신고 및 첨부자료', 100),
    ('corporate_tax', '법인세자료', '법인세 신고, 세무조정, 세액공제 관련 자료', 110),
    ('legal_contract', '계약서 및 법무자료', '계약, 약정, 소송, 법무 조회 관련 자료', 120),
    ('industry_specific', '업종별 특수자료', '제조, 건설, 이커머스, 병의원, 스타트업 특수자료', 130)
)
INSERT INTO document_categories (code, name, description, sort_order)
SELECT code, name, description, sort_order
FROM category_seed
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

WITH document_seed(category_code, code, name, sort_order) AS (
  VALUES
    ('company_basic', 'business_registration_certificate', '사업자등록증', 10),
    ('company_basic', 'corporate_registry_certificate', '법인등기사항전부증명서', 20),
    ('company_basic', 'corporate_registry_extract', '법인등기부등본', 30),
    ('company_basic', 'articles_of_incorporation', '정관', 40),
    ('company_basic', 'shareholder_register', '주주명부', 50),
    ('company_basic', 'executive_register', '임원명부', 60),
    ('company_basic', 'organization_chart', '조직도', 70),
    ('company_basic', 'company_profile', '회사소개서', 80),
    ('company_basic', 'business_plan', '사업계획서', 90),
    ('company_basic', 'product_service_list', '주요 제품 및 서비스 목록', 100),
    ('company_basic', 'shareholder_meeting_minutes', '주주총회 의사록', 110),
    ('company_basic', 'board_meeting_minutes', '이사회 의사록', 120),
    ('company_basic', 'accounting_policy', '회계규정', 130),
    ('company_basic', 'hr_policy', '인사규정', 140),
    ('company_basic', 'approval_authority_policy', '전결규정', 150),
    ('company_basic', 'related_party_status', '특수관계자 현황표', 160),

    ('accounting_closing', 'general_ledger', '총계정원장', 10),
    ('accounting_closing', 'account_ledger', '계정별원장', 20),
    ('accounting_closing', 'trial_balance', '합계잔액시산표', 30),
    ('accounting_closing', 'statement_of_financial_position', '재무상태표', 40),
    ('accounting_closing', 'income_statement', '손익계산서', 50),
    ('accounting_closing', 'statement_of_comprehensive_income', '포괄손익계산서', 60),
    ('accounting_closing', 'manufacturing_cost_statement', '제조원가명세서', 70),
    ('accounting_closing', 'construction_cost_statement', '공사원가명세서', 80),
    ('accounting_closing', 'cash_flow_statement', '현금흐름표', 90),
    ('accounting_closing', 'statement_of_changes_in_equity', '자본변동표', 100),
    ('accounting_closing', 'retained_earnings_appropriation_statement', '이익잉여금처분계산서', 110),
    ('accounting_closing', 'deficit_disposition_statement', '결손금처리계산서', 120),
    ('accounting_closing', 'voucher', '전표', 130),
    ('accounting_closing', 'journal', '분개장', 140),
    ('accounting_closing', 'monthly_sales_summary', '월별 매출 집계표', 150),
    ('accounting_closing', 'monthly_purchase_summary', '월별 매입 집계표', 160),
    ('accounting_closing', 'closing_adjustment_statement', '결산 조정 내역서', 170),
    ('accounting_closing', 'tax_adjustment_statement', '세무조정계산서', 180),
    ('accounting_closing', 'audit_report', '감사보고서', 190),
    ('accounting_closing', 'standard_financial_statement_certificate', '표준재무제표증명', 200),

    ('revenue', 'sales_tax_invoice', '매출 세금계산서', 10),
    ('revenue', 'sales_invoice', '매출 계산서', 20),
    ('revenue', 'sales_tax_invoice_summary_by_customer', '매출처별 세금계산서합계표', 30),
    ('revenue', 'sales_invoice_summary_by_customer', '매출처별 계산서합계표', 40),
    ('revenue', 'card_sales_statement', '카드매출 내역', 50),
    ('revenue', 'cash_receipt_sales_statement', '현금영수증 매출 내역', 60),
    ('revenue', 'credit_card_sales_slip_issue_summary', '신용카드매출전표 발행집계표', 70),
    ('revenue', 'cash_sales_statement', '현금매출명세서', 80),
    ('revenue', 'pos_sales_data', 'POS 매출자료', 90),
    ('revenue', 'platform_sales_settlement_data', '플랫폼 매출 정산자료', 100),
    ('revenue', 'pg_settlement_data', 'PG 정산자료', 110),
    ('revenue', 'sales_detail_by_customer', '거래처별 매출 명세서', 120),
    ('revenue', 'sales_detail_by_product', '제품별 매출 명세서', 130),
    ('revenue', 'sales_detail_by_service', '서비스별 매출 명세서', 140),
    ('revenue', 'accounts_receivable_balance_schedule', '매출채권 잔액명세서', 150),
    ('revenue', 'accounts_receivable_aging_report', '매출채권 연령분석표', 160),
    ('revenue', 'allowance_for_doubtful_accounts_calculation', '대손충당금 산정내역서', 170),
    ('revenue', 'major_sales_contract', '주요 매출계약서', 180),
    ('revenue', 'export_declaration_certificate', '수출신고필증', 190),
    ('revenue', 'commercial_invoice', '상업송장', 200),
    ('revenue', 'packing_list', '포장명세서', 210),
    ('revenue', 'bill_of_lading', '선하증권', 220),
    ('revenue', 'foreign_exchange_earning_statement', '외화획득명세서', 230),

    ('purchase_expense', 'purchase_tax_invoice', '매입 세금계산서', 10),
    ('purchase_expense', 'purchase_invoice', '매입 계산서', 20),
    ('purchase_expense', 'purchase_tax_invoice_summary_by_vendor', '매입처별 세금계산서합계표', 30),
    ('purchase_expense', 'purchase_invoice_summary_by_vendor', '매입처별 계산서합계표', 40),
    ('purchase_expense', 'credit_card_usage_statement', '신용카드 사용내역', 50),
    ('purchase_expense', 'corporate_card_usage_statement', '법인카드 사용명세서', 60),
    ('purchase_expense', 'cash_receipt', '현금영수증', 70),
    ('purchase_expense', 'simple_receipt', '간이영수증', 80),
    ('purchase_expense', 'transaction_statement', '거래명세서', 90),
    ('purchase_expense', 'payment_request_form', '지출결의서', 100),
    ('purchase_expense', 'employee_expense_report', '임직원 경비정산서', 110),
    ('purchase_expense', 'entertainment_expense_schedule', '접대비 명세서', 120),
    ('purchase_expense', 'travel_expense_schedule', '출장비 명세서', 130),
    ('purchase_expense', 'employee_benefit_supporting_document', '복리후생비 증빙자료', 140),
    ('purchase_expense', 'advertising_expense_execution_statement', '광고선전비 집행내역서', 150),
    ('purchase_expense', 'commission_fee_contract', '지급수수료 계약서', 160),
    ('purchase_expense', 'outsourcing_service_contract', '외주용역계약서', 170),
    ('purchase_expense', 'outsourcing_acceptance_document', '외주비 검수자료', 180),
    ('purchase_expense', 'expense_approval_evidence', '비용 지출 승인자료', 190),
    ('purchase_expense', 'credit_card_sales_slip_receipt_statement', '신용카드매출전표 수령명세서', 200),
    ('purchase_expense', 'non_deductible_input_vat_statement', '매입세액 불공제 내역서', 210),

    ('finance_cash', 'bank_account_list', '은행 계좌 목록', 10),
    ('finance_cash', 'bank_balance_certificate', '예금잔액증명서', 20),
    ('finance_cash', 'bank_transaction_statement', '계좌거래내역', 30),
    ('finance_cash', 'bankbook_copy', '통장 사본', 40),
    ('finance_cash', 'daily_cash_report', '자금일보', 50),
    ('finance_cash', 'cash_flow_budget_actual_report', '자금수지표', 60),
    ('finance_cash', 'borrowings_schedule', '차입금 명세서', 70),
    ('finance_cash', 'loan_agreement', '대출약정서', 80),
    ('finance_cash', 'interest_rate_terms_sheet', '이자율 조건표', 90),
    ('finance_cash', 'maturity_terms_sheet', '만기 조건표', 100),
    ('finance_cash', 'collateral_provided_schedule', '담보 제공 내역서', 110),
    ('finance_cash', 'guarantee_provided_schedule', '보증 제공 내역서', 120),
    ('finance_cash', 'corporate_card_statement', '법인카드 명세서', 130),
    ('finance_cash', 'financial_institution_confirmation', '금융기관조회서', 140),
    ('finance_cash', 'foreign_currency_deposit_schedule', '외화예금 명세서', 150),
    ('finance_cash', 'foreign_currency_borrowings_schedule', '외화차입금 명세서', 160),

    ('receivable_payable', 'accounts_receivable_balance_by_customer', '거래처별 매출채권 잔액명세서', 10),
    ('receivable_payable', 'accounts_payable_balance_by_vendor', '거래처별 매입채무 잔액명세서', 20),
    ('receivable_payable', 'other_receivables_schedule', '미수금 명세서', 30),
    ('receivable_payable', 'accrued_payables_schedule', '미지급금 명세서', 40),
    ('receivable_payable', 'advance_payments_schedule', '선급금 명세서', 50),
    ('receivable_payable', 'advances_received_schedule', '선수금 명세서', 60),
    ('receivable_payable', 'temporary_payments_schedule', '가지급금 명세서', 70),
    ('receivable_payable', 'temporary_receipts_schedule', '가수금 명세서', 80),
    ('receivable_payable', 'receivable_payable_confirmation', '채권채무조회서', 90),
    ('receivable_payable', 'receivable_payable_confirmation_target_list', '채권채무조회 발송대상 목록', 100),
    ('receivable_payable', 'business_partner_address_book', '거래처 주소록', 110),
    ('receivable_payable', 'long_outstanding_receivables_statement', '장기 미회수 채권 내역서', 120),
    ('receivable_payable', 'bad_debt_write_off_evidence', '대손 처리 근거자료', 130),

    ('inventory', 'inventory_schedule_by_item', '품목별 재고명세서', 10),
    ('inventory', 'inventory_movement_ledger', '재고수불부', 20),
    ('inventory', 'inventory_count_sheet', '재고실사표', 30),
    ('inventory', 'inventory_count_result_report', '재고실사 결과보고서', 40),
    ('inventory', 'ending_inventory_valuation_document', '기말재고 평가자료', 50),
    ('inventory', 'cost_calculation_document', '원가 산정자료', 60),
    ('inventory', 'lower_of_cost_or_market_valuation_document', '저가법 평가자료', 70),
    ('inventory', 'scrapped_inventory_statement', '폐기 재고 내역서', 80),
    ('inventory', 'inventory_shrinkage_statement', '감모 재고 내역서', 90),
    ('inventory', 'defective_inventory_statement', '불량 재고 내역서', 100),
    ('inventory', 'cutoff_inventory_movement_statement', '결산일 전후 입출고 내역서', 110),

    ('fixed_intangible_assets', 'fixed_asset_register', '유형자산대장', 10),
    ('fixed_intangible_assets', 'fixed_asset_acquisition_contract', '유형자산 취득계약서', 20),
    ('fixed_intangible_assets', 'fixed_asset_purchase_tax_invoice', '유형자산 매입 세금계산서', 30),
    ('fixed_intangible_assets', 'fixed_asset_disposal_statement', '유형자산 처분내역서', 40),
    ('fixed_intangible_assets', 'depreciation_expense_schedule', '감가상각비 명세서', 50),
    ('fixed_intangible_assets', 'vehicle_registration_certificate', '차량등록증', 60),
    ('fixed_intangible_assets', 'real_estate_registry_certificate', '부동산 등기사항전부증명서', 70),
    ('fixed_intangible_assets', 'lease_agreement', '임대차계약서', 80),
    ('fixed_intangible_assets', 'deposit_schedule', '보증금 명세서', 90),
    ('fixed_intangible_assets', 'development_cost_schedule', '개발비 명세서', 100),
    ('fixed_intangible_assets', 'software_license_agreement', '소프트웨어 사용권 계약서', 110),
    ('fixed_intangible_assets', 'patent_registration_certificate', '특허권 등록증', 120),
    ('fixed_intangible_assets', 'trademark_registration_certificate', '상표권 등록증', 130),
    ('fixed_intangible_assets', 'intangible_asset_impairment_review', '무형자산 손상검토 자료', 140),

    ('payroll_withholding', 'employee_roster', '임직원 명부', 10),
    ('payroll_withholding', 'employment_contract', '근로계약서', 20),
    ('payroll_withholding', 'payroll_register', '급여대장', 30),
    ('payroll_withholding', 'bonus_payment_statement', '상여금 지급내역서', 40),
    ('payroll_withholding', 'severance_pay_calculation_document', '퇴직금 산정자료', 50),
    ('payroll_withholding', 'retirement_pension_enrollment_statement', '퇴직연금 가입내역서', 60),
    ('payroll_withholding', 'withholding_tax_payment_statement', '원천징수이행상황신고서', 70),
    ('payroll_withholding', 'earned_income_payment_statement', '근로소득 지급명세서', 80),
    ('payroll_withholding', 'business_income_payment_statement', '사업소득 지급명세서', 90),
    ('payroll_withholding', 'daily_worker_income_payment_statement', '일용근로소득 지급명세서', 100),
    ('payroll_withholding', 'retirement_income_payment_statement', '퇴직소득 지급명세서', 110),
    ('payroll_withholding', 'simplified_payment_statement', '간이지급명세서', 120),
    ('payroll_withholding', 'four_major_insurance_billing_statement', '4대보험 고지내역서', 130),
    ('payroll_withholding', 'four_major_insurance_payment_statement', '4대보험 납부내역서', 140),
    ('payroll_withholding', 'year_end_tax_settlement_document', '연말정산 자료', 150),
    ('payroll_withholding', 'stock_option_grant_agreement', '스톡옵션 부여계약서', 160),
    ('payroll_withholding', 'share_based_compensation_valuation_document', '주식보상 평가자료', 170),

    ('vat', 'vat_return', '부가가치세 신고서', 10),
    ('vat', 'zero_rated_vat_attachment', '영세율 첨부서류', 90),
    ('vat', 'deemed_input_vat_credit_report', '의제매입세액공제 신고서', 100),
    ('vat', 'bad_debt_vat_credit_report', '대손세액공제 신고서', 110),
    ('vat', 'real_estate_rental_supply_value_statement', '부동산임대공급가액명세서', 120),
    ('vat', 'building_depreciable_asset_acquisition_statement', '건물 등 감가상각자산 취득명세서', 140),

    ('corporate_tax', 'corporate_tax_return', '법인세 과세표준 및 세액신고서', 10),
    ('corporate_tax', 'depreciation_adjustment_schedule', '감가상각비 조정명세서', 70),
    ('corporate_tax', 'entertainment_expense_adjustment_schedule', '접대비 조정명세서', 80),
    ('corporate_tax', 'donation_adjustment_schedule', '기부금 조정명세서', 90),
    ('corporate_tax', 'retirement_benefit_allowance_adjustment_schedule', '퇴직급여충당금 조정명세서', 100),
    ('corporate_tax', 'bad_debt_allowance_adjustment_schedule', '대손충당금 조정명세서', 110),
    ('corporate_tax', 'inventory_valuation_adjustment_schedule', '재고자산 평가조정명세서', 120),
    ('corporate_tax', 'research_hr_development_tax_credit_application', '연구인력개발비 세액공제 신청서', 130),
    ('corporate_tax', 'integrated_investment_tax_credit_application', '통합투자세액공제 신청서', 140),
    ('corporate_tax', 'tax_loss_carryforward_schedule', '이월결손금 명세서', 150),
    ('corporate_tax', 'related_party_transaction_statement', '특수관계자 거래명세서', 160),

    ('legal_contract', 'major_purchase_contract', '주요 매입계약서', 20),
    ('legal_contract', 'borrowing_agreement', '차입약정서', 50),
    ('legal_contract', 'lending_agreement', '대여약정서', 60),
    ('legal_contract', 'investment_agreement', '투자계약서', 70),
    ('legal_contract', 'shareholders_agreement', '주주간계약서', 80),
    ('legal_contract', 'license_agreement', '라이선스 계약서', 90),
    ('legal_contract', 'collateral_agreement', '담보계약서', 100),
    ('legal_contract', 'guarantee_agreement', '보증계약서', 110),
    ('legal_contract', 'litigation_status_schedule', '소송 현황표', 120),
    ('legal_contract', 'attorney_inquiry_letter', '변호사 조회서', 130),
    ('legal_contract', 'certified_content_mail', '내용증명', 140),
    ('legal_contract', 'dispute_related_document', '분쟁 관련 자료', 150),

    ('industry_specific', 'bill_of_materials', '자재명세서', 10),
    ('industry_specific', 'daily_production_report', '생산일보', 20),
    ('industry_specific', 'raw_material_movement_ledger', '원재료 수불부', 30),
    ('industry_specific', 'outsourcing_processing_fee_schedule', '외주가공비 명세서', 50),
    ('industry_specific', 'construction_contract', '공사계약서', 60),
    ('industry_specific', 'percentage_of_completion_calculation', '진행률 산정자료', 80),
    ('industry_specific', 'subcontract_agreement', '하도급계약서', 90),
    ('industry_specific', 'unbilled_construction_schedule', '미청구공사 명세서', 110),
    ('industry_specific', 'industry_platform_settlement_data', '플랫폼 정산자료', 120),
    ('industry_specific', 'shipping_fee_settlement_data', '배송비 정산자료', 140),
    ('industry_specific', 'return_statement', '반품 내역서', 150),
    ('industry_specific', 'refund_statement', '환불 내역서', 160),
    ('industry_specific', 'coupon_settlement_data', '쿠폰 정산자료', 170),
    ('industry_specific', 'point_settlement_data', '포인트 정산자료', 180),
    ('industry_specific', 'nhis_payment_statement', '건강보험공단 지급내역서', 190),
    ('industry_specific', 'non_insured_medical_sales_data', '비급여 매출자료', 200),
    ('industry_specific', 'medical_equipment_lease_agreement', '의료장비 리스계약서', 210),
    ('industry_specific', 'medical_equipment_purchase_document', '의료장비 구입자료', 220),
    ('industry_specific', 'safe_agreement', 'SAFE 계약서', 230),
    ('industry_specific', 'convertible_bond_subscription_agreement', '전환사채 인수계약서', 240),
    ('industry_specific', 'redeemable_convertible_preferred_share_investment_agreement', '상환전환우선주 투자계약서', 250),
    ('industry_specific', 'government_grant_agreement', '정부지원금 협약서', 260),
    ('industry_specific', 'rd_expense_usage_statement', '연구개발비 사용명세서', 270),
    ('industry_specific', 'project_expense_supporting_document', '과제비 증빙자료', 280)
)
INSERT INTO document_types (category_id, code, name, sort_order)
SELECT c.id, s.code, s.name, s.sort_order
FROM document_seed s
JOIN document_categories c ON c.code = s.category_code
ON CONFLICT (code) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name = EXCLUDED.name,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
