-- AuditMind request template master seed.
-- These rows are accounting-firm work packages. They are not document categories.
-- Template-document defaults should be maintained separately in request_template_documents.

WITH template_seed(code, name, service_area, description, sort_order) AS (
  VALUES
    ('external_audit', '외부감사', '회계·감사·인증', '법정 외부감사를 위한 자료 요청 서비스', 1010),
    ('voluntary_audit', '임의감사', '회계·감사·인증', '법정 의무가 아닌 임의 감사 업무를 위한 자료 요청 서비스', 1020),
    ('financial_statement_review', '재무제표 검토', '회계·감사·인증', '재무제표 검토 업무를 위한 자료 요청 서비스', 1030),
    ('internal_control_audit', '내부회계관리제도 감사', '회계·감사·인증', '내부회계관리제도 감사 업무를 위한 자료 요청 서비스', 1040),
    ('internal_control_review', '내부회계관리제도 검토', '회계·감사·인증', '내부회계관리제도 검토 업무를 위한 자료 요청 서비스', 1050),
    ('agreed_upon_procedures', '합의된 절차 수행', '회계·감사·인증', '합의된 절차 수행 보고를 위한 자료 요청 서비스', 1060),
    ('grant_settlement_verification', '보조금 정산 검증', '회계·감사·인증', '보조금 정산 검증 업무를 위한 자료 요청 서비스', 1070),
    ('public_interest_entity_audit', '공익법인 회계감사', '회계·감사·인증', '공익법인 회계감사를 위한 자료 요청 서비스', 1080),
    ('nonprofit_audit', '비영리법인 회계감사', '회계·감사·인증', '비영리법인 회계감사를 위한 자료 요청 서비스', 1090),
    ('special_purpose_financial_statement_audit', '특수목적 재무제표 감사', '회계·감사·인증', '특수목적 재무제표 감사 업무를 위한 자료 요청 서비스', 1100),
    ('consolidated_financial_statement_audit', '연결재무제표 감사', '회계·감사·인증', '연결재무제표 감사 업무를 위한 자료 요청 서비스', 1110),
    ('audit_response_package_preparation', '감사 대응 자료 준비', '회계·감사·인증', '감사 대응을 위한 자료 패키지 준비 서비스', 1120),
    ('pre_audit_finance_readiness', '감사 전 재무자료 정비', '회계·감사·인증', '감사 착수 전 재무자료 정비를 위한 요청 서비스', 1130),

    ('bookkeeping_outsourcing', '기장대리', '세무신고·세무대리', '기장대리 업무를 위한 자료 요청 서비스', 2010),
    ('vat_filing', '부가가치세 신고', '세무신고·세무대리', '부가가치세 신고를 위한 자료 요청 서비스', 2020),
    ('corporate_income_tax_filing', '법인세 신고', '세무신고·세무대리', '법인세 신고를 위한 자료 요청 서비스', 2030),
    ('corporate_tax_adjustment', '법인세 세무조정', '세무신고·세무대리', '법인세 세무조정 업무를 위한 자료 요청 서비스', 2040),
    ('individual_income_tax_filing', '종합소득세 신고', '세무신고·세무대리', '종합소득세 신고를 위한 자료 요청 서비스', 2050),
    ('withholding_tax_filing', '원천세 신고', '세무신고·세무대리', '원천세 신고를 위한 자료 요청 서비스', 2060),
    ('year_end_tax_settlement', '연말정산', '세무신고·세무대리', '연말정산 업무를 위한 자료 요청 서비스', 2070),
    ('payment_statement_submission', '지급명세서 제출', '세무신고·세무대리', '지급명세서 제출 업무를 위한 자료 요청 서비스', 2080),
    ('social_insurance_filing_support', '4대보험 신고 지원', '세무신고·세무대리', '4대보험 신고 지원 업무를 위한 자료 요청 서비스', 2090),
    ('local_tax_filing', '지방세 신고', '세무신고·세무대리', '지방세 신고 업무를 위한 자료 요청 서비스', 2100),
    ('capital_gains_tax_filing', '양도소득세 신고', '세무신고·세무대리', '양도소득세 신고 업무를 위한 자료 요청 서비스', 2110),
    ('securities_transaction_tax_filing', '증권거래세 신고', '세무신고·세무대리', '증권거래세 신고 업무를 위한 자료 요청 서비스', 2120),
    ('inheritance_tax_filing', '상속세 신고', '세무신고·세무대리', '상속세 신고 업무를 위한 자료 요청 서비스', 2130),
    ('gift_tax_filing', '증여세 신고', '세무신고·세무대리', '증여세 신고 업무를 위한 자료 요청 서비스', 2140),
    ('tax_audit_response', '세무조사 대응', '세무신고·세무대리', '세무조사 대응 업무를 위한 자료 요청 서비스', 2150),
    ('pre_tax_assessment_review_claim', '과세전적부심사 청구', '세무신고·세무대리', '과세전적부심사 청구 업무를 위한 자료 요청 서비스', 2160),
    ('tax_objection', '이의신청', '세무신고·세무대리', '이의신청 업무를 위한 자료 요청 서비스', 2170),
    ('tax_review_claim', '심사청구', '세무신고·세무대리', '심사청구 업무를 위한 자료 요청 서비스', 2180),
    ('tax_tribunal_appeal', '심판청구', '세무신고·세무대리', '심판청구 업무를 위한 자료 요청 서비스', 2190),
    ('tax_correction_claim', '경정청구', '세무신고·세무대리', '경정청구 업무를 위한 자료 요청 서비스', 2200),
    ('tax_ruling_request', '세법 유권해석 질의', '세무신고·세무대리', '세법 유권해석 질의 업무를 위한 자료 요청 서비스', 2210),
    ('tax_incentive_review', '조세특례 검토', '세무신고·세무대리', '조세특례 검토 업무를 위한 자료 요청 서비스', 2220),
    ('research_development_tax_credit_review', '연구인력개발비 세액공제 검토', '세무신고·세무대리', '연구인력개발비 세액공제 검토 업무를 위한 자료 요청 서비스', 2230),
    ('investment_tax_credit_review', '투자세액공제 검토', '세무신고·세무대리', '투자세액공제 검토 업무를 위한 자료 요청 서비스', 2240),

    ('transfer_pricing_documentation', '이전가격 문서화', '국제조세·이전가격', '이전가격 문서화 업무를 위한 자료 요청 서비스', 3010),
    ('arm_length_pricing_method_review', '정상가격 산출방법 검토', '국제조세·이전가격', '정상가격 산출방법 검토 업무를 위한 자료 요청 서비스', 3020),
    ('cross_border_tax_review', '국제거래 세무검토', '국제조세·이전가격', '국제거래 세무검토 업무를 위한 자료 요청 서비스', 3030),
    ('foreign_related_party_transaction_review', '국외특수관계자 거래 검토', '국제조세·이전가격', '국외특수관계자 거래 검토 업무를 위한 자료 요청 서비스', 3040),
    ('withholding_tax_review', '원천징수 검토', '국제조세·이전가격', '원천징수 검토 업무를 위한 자료 요청 서비스', 3050),
    ('tax_treaty_application_review', '조세조약 적용 검토', '국제조세·이전가격', '조세조약 적용 검토 업무를 위한 자료 요청 서비스', 3060),
    ('overseas_subsidiary_tax_package_review', '해외법인 세무 패키지 검토', '국제조세·이전가격', '해외법인 세무 패키지 검토 업무를 위한 자료 요청 서비스', 3070),
    ('global_minimum_tax_response', '글로벌 최저한세 대응', '국제조세·이전가격', '글로벌 최저한세 대응 업무를 위한 자료 요청 서비스', 3080),
    ('customs_and_trade_tax_review', '관세 및 국제통상 세무 검토', '국제조세·이전가격', '관세 및 국제통상 세무 검토 업무를 위한 자료 요청 서비스', 3090),

    ('monthly_bookkeeping', '월간 기장', '회계처리·결산·BPO', '월간 기장 업무를 위한 자료 요청 서비스', 4010),
    ('monthly_closing', '월간 결산', '회계처리·결산·BPO', '월간 결산 업무를 위한 자료 요청 서비스', 4020),
    ('financial_statement_preparation_support', '재무제표 작성 지원', '회계처리·결산·BPO', '재무제표 작성 지원 업무를 위한 자료 요청 서비스', 4030),
    ('consolidation_closing_support', '연결결산 지원', '회계처리·결산·BPO', '연결결산 지원 업무를 위한 자료 요청 서비스', 4040),
    ('sales_settlement_management', '매출 정산 관리', '회계처리·결산·BPO', '매출 정산 관리 업무를 위한 자료 요청 서비스', 4050),
    ('platform_sales_settlement_review', '플랫폼 매출 정산 검토', '회계처리·결산·BPO', '플랫폼 매출 정산 검토 업무를 위한 자료 요청 서비스', 4060),
    ('pg_settlement_review', 'PG 정산 검토', '회계처리·결산·BPO', 'PG 정산 검토 업무를 위한 자료 요청 서비스', 4070),
    ('inventory_movement_management', '재고 수불 관리', '회계처리·결산·BPO', '재고 수불 관리 업무를 위한 자료 요청 서비스', 4080),
    ('cost_closing', '원가 결산', '회계처리·결산·BPO', '원가 결산 업무를 위한 자료 요청 서비스', 4090),
    ('payroll_outsourcing', '급여 아웃소싱', '회계처리·결산·BPO', '급여 아웃소싱 업무를 위한 자료 요청 서비스', 4100),
    ('daily_cash_report_preparation', '자금일보 작성', '회계처리·결산·BPO', '자금일보 작성 업무를 위한 자료 요청 서비스', 4110),
    ('cash_flow_plan_preparation', '자금수지표 작성', '회계처리·결산·BPO', '자금수지표 작성 업무를 위한 자료 요청 서비스', 4120),
    ('receivable_payable_balance_cleanup', '채권채무 잔액 정리', '회계처리·결산·BPO', '채권채무 잔액 정리 업무를 위한 자료 요청 서비스', 4130),
    ('accrual_balance_cleanup', '미수금·미지급금 정리', '회계처리·결산·BPO', '미수금·미지급금 정리 업무를 위한 자료 요청 서비스', 4140),
    ('accounting_book_cleanup', '회계 장부 클린업', '회계처리·결산·BPO', '회계 장부 클린업 업무를 위한 자료 요청 서비스', 4150),
    ('accounting_system_migration_support', '회계 시스템 전환 지원', '회계처리·결산·BPO', '회계 시스템 전환 지원 업무를 위한 자료 요청 서비스', 4160),

    ('financial_due_diligence', '재무실사', '재무자문·거래자문', '재무실사 업무를 위한 자료 요청 서비스', 5010),
    ('tax_due_diligence', '세무실사', '재무자문·거래자문', '세무실사 업무를 위한 자료 요청 서비스', 5020),
    ('vendor_due_diligence', '매도자 실사', '재무자문·거래자문', '매도자 실사 업무를 위한 자료 요청 서비스', 5030),
    ('post_acquisition_finance_cleanup', '인수 후 재무자료 정비', '재무자문·거래자문', '인수 후 재무자료 정비 업무를 위한 자료 요청 서비스', 5040),
    ('enterprise_valuation', '기업가치평가', '재무자문·거래자문', '기업가치평가 업무를 위한 자료 요청 서비스', 5050),
    ('equity_valuation', '주식가치평가', '재무자문·거래자문', '주식가치평가 업무를 위한 자료 요청 서비스', 5060),
    ('business_valuation', '사업가치평가', '재무자문·거래자문', '사업가치평가 업무를 위한 자료 요청 서비스', 5070),
    ('fundraising_material_review', '투자유치 자료 검토', '재무자문·거래자문', '투자유치 자료 검토 업무를 위한 자료 요청 서비스', 5080),
    ('ma_transaction_advisory', 'M&A 거래 자문', '재무자문·거래자문', 'M&A 거래 자문 업무를 위한 자료 요청 서비스', 5090),
    ('financial_model_review', '재무모델 검토', '재무자문·거래자문', '재무모델 검토 업무를 위한 자료 요청 서비스', 5100),
    ('business_plan_review', '사업계획 검토', '재무자문·거래자문', '사업계획 검토 업무를 위한 자료 요청 서비스', 5110),
    ('impairment_test_review', '손상검토', '재무자문·거래자문', '손상검토 업무를 위한 자료 요청 서비스', 5120),
    ('purchase_price_allocation', '구매가격배분', '재무자문·거래자문', '구매가격배분 업무를 위한 자료 요청 서비스', 5130),
    ('goodwill_valuation', '영업권 평가', '재무자문·거래자문', '영업권 평가 업무를 위한 자료 요청 서비스', 5140),
    ('stock_option_valuation', '주식매수선택권 평가', '재무자문·거래자문', '주식매수선택권 평가 업무를 위한 자료 요청 서비스', 5150),
    ('convertible_bond_valuation', '전환사채 평가', '재무자문·거래자문', '전환사채 평가 업무를 위한 자료 요청 서비스', 5160),
    ('redeemable_convertible_preferred_share_valuation', '상환전환우선주 평가', '재무자문·거래자문', '상환전환우선주 평가 업무를 위한 자료 요청 서비스', 5170),

    ('k_ifrs_conversion_advisory', 'K-IFRS 전환 자문', '회계자문·재무보고 자문', 'K-IFRS 전환 자문 업무를 위한 자료 요청 서비스', 6010),
    ('k_gaap_accounting_treatment_review', '일반기업회계기준 회계처리 검토', '회계자문·재무보고 자문', '일반기업회계기준 회계처리 검토 업무를 위한 자료 요청 서비스', 6020),
    ('revenue_recognition_accounting_review', '수익인식 회계처리 검토', '회계자문·재무보고 자문', '수익인식 회계처리 검토 업무를 위한 자료 요청 서비스', 6030),
    ('lease_accounting_review', '리스 회계처리 검토', '회계자문·재무보고 자문', '리스 회계처리 검토 업무를 위한 자료 요청 서비스', 6040),
    ('financial_instrument_accounting_review', '금융상품 회계처리 검토', '회계자문·재무보고 자문', '금융상품 회계처리 검토 업무를 위한 자료 요청 서비스', 6050),
    ('share_based_payment_accounting_review', '주식보상 회계처리 검토', '회계자문·재무보고 자문', '주식보상 회계처리 검토 업무를 위한 자료 요청 서비스', 6060),
    ('consolidation_scope_review', '연결범위 검토', '회계자문·재무보고 자문', '연결범위 검토 업무를 위한 자료 요청 서비스', 6070),
    ('accounting_policy_setup', '회계정책 수립', '회계자문·재무보고 자문', '회계정책 수립 업무를 위한 자료 요청 서비스', 6080),
    ('closing_process_improvement', '결산 프로세스 개선', '회계자문·재무보고 자문', '결산 프로세스 개선 업무를 위한 자료 요청 서비스', 6090),
    ('disclosure_material_preparation_support', '공시자료 작성 지원', '회계자문·재무보고 자문', '공시자료 작성 지원 업무를 위한 자료 요청 서비스', 6100),
    ('ipo_financial_reporting_preparation', 'IPO 재무보고 준비', '회계자문·재무보고 자문', 'IPO 재무보고 준비 업무를 위한 자료 요청 서비스', 6110),
    ('management_accounting_setup', '내부관리회계 체계 수립', '회계자문·재무보고 자문', '내부관리회계 체계 수립 업무를 위한 자료 요청 서비스', 6120),

    ('fundraising_financial_package_preparation', '투자유치 재무자료 준비', '스타트업·성장기업 특화', '투자유치 재무자료 준비 업무를 위한 자료 요청 서비스', 7010),
    ('investor_reporting_material_review', '투자자 보고자료 검토', '스타트업·성장기업 특화', '투자자 보고자료 검토 업무를 위한 자료 요청 서비스', 7020),
    ('stock_option_grant_material_review', '스톡옵션 부여자료 검토', '스타트업·성장기업 특화', '스톡옵션 부여자료 검토 업무를 위한 자료 요청 서비스', 7030),
    ('government_grant_settlement', '정부지원금 정산', '스타트업·성장기업 특화', '정부지원금 정산 업무를 위한 자료 요청 서비스', 7040),
    ('rd_project_cost_settlement', 'R&D 과제비 정산', '스타트업·성장기업 특화', 'R&D 과제비 정산 업무를 위한 자료 요청 서비스', 7050),
    ('safe_agreement_accounting_review', 'SAFE 계약 회계검토', '스타트업·성장기업 특화', 'SAFE 계약 회계검토 업무를 위한 자료 요청 서비스', 7060),
    ('convertible_bond_accounting_review', '전환사채 회계검토', '스타트업·성장기업 특화', '전환사채 회계검토 업무를 위한 자료 요청 서비스', 7070),
    ('redeemable_convertible_preferred_share_accounting_review', '상환전환우선주 회계검토', '스타트업·성장기업 특화', '상환전환우선주 회계검토 업무를 위한 자료 요청 서비스', 7080),
    ('venture_company_certification_preparation', '벤처기업 인증 자료 준비', '스타트업·성장기업 특화', '벤처기업 인증 자료 준비 업무를 위한 자료 요청 서비스', 7090),
    ('startup_incorporation_accounting_tax_setup', '초기 법인 설립 회계·세무 세팅', '스타트업·성장기업 특화', '초기 법인 설립 회계·세무 세팅 업무를 위한 자료 요청 서비스', 7100),
    ('virtual_cfo_support', '가상 CFO 지원', '스타트업·성장기업 특화', '가상 CFO 지원 업무를 위한 자료 요청 서비스', 7110),
    ('management_report_preparation_support', '경영관리 리포트 작성 지원', '스타트업·성장기업 특화', '경영관리 리포트 작성 지원 업무를 위한 자료 요청 서비스', 7120),

    ('ecommerce_settlement_review', '이커머스 정산 검토', '고객 산업별 특수', '이커머스 정산 검토 업무를 위한 자료 요청 서비스', 8010),
    ('manufacturing_cost_closing', '제조업 원가 결산', '고객 산업별 특수', '제조업 원가 결산 업무를 위한 자료 요청 서비스', 8020),
    ('construction_progress_rate_review', '건설업 진행률 검토', '고객 산업별 특수', '건설업 진행률 검토 업무를 위한 자료 요청 서비스', 8030),
    ('medical_clinic_revenue_data_review', '병의원 매출자료 검토', '고객 산업별 특수', '병의원 매출자료 검토 업무를 위한 자료 요청 서비스', 8040),
    ('franchise_store_settlement_review', '프랜차이즈 가맹점 정산 검토', '고객 산업별 특수', '프랜차이즈 가맹점 정산 검토 업무를 위한 자료 요청 서비스', 8050),
    ('platform_operator_settlement_review', '플랫폼 사업자 정산 검토', '고객 산업별 특수', '플랫폼 사업자 정산 검토 업무를 위한 자료 요청 서비스', 8060),
    ('import_export_transaction_tax_review', '수출입 거래 세무검토', '고객 산업별 특수', '수출입 거래 세무검토 업무를 위한 자료 요청 서비스', 8070),
    ('public_interest_entity_closing_tax_review', '공익법인 결산 및 세무검토', '고객 산업별 특수', '공익법인 결산 및 세무검토 업무를 위한 자료 요청 서비스', 8080)
)
INSERT INTO request_templates (code, name, service_area, description, sort_order)
SELECT code, name, service_area, description, sort_order
FROM template_seed
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  service_area = EXCLUDED.service_area,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
