export const accountantConsoleContent = {
  brand: {
    eyebrow: "AuditMind",
    title: "회계사 콘솔",
    firmName: "AuditMind 파트너스",
    userName: "데모 계정",
  },
  nav: [
    { label: "대시보드", href: "/console", active: true, count: "" },
    { label: "고객사 관리", href: "/console?page=customers", active: false, count: "" },
    { label: "제출자료 검토", href: "/console?page=review", active: false, count: "" },
    { label: "서비스 관리", href: "/console?page=templates", active: false, count: "" },
  ],
  summary: [
    {
      label: "검토 대기 자료",
      value: "0",
      helper: "신규 0건",
      hoverTitle: "신규 제출 고객사",
      customers: [],
      tone: "primary",
      configurable: false,
    },
    {
      label: "자료 미제출 고객사",
      value: "0",
      alertDays: 5,
      dueCustomers: [],
      tone: "primary",
      settingType: "due",
      configurable: false,
    },
    {
      label: "고객사 요청사항",
      value: "0",
      helper: "신규 0건",
      hoverTitle: "요청사항 입력 고객사",
      customers: [],
      tone: "primary",
      configurable: false,
    },
  ],
  notifications: [],
  queue: [],
};
