export const accountantConsoleContent = {
  brand: {
    eyebrow: "AuditMind",
    title: "회계사 콘솔",
    firmName: "AuditMind 파트너스",
    userName: "김세무 매니저",
  },
  nav: [
    { label: "대시보드", href: "/", active: true, count: "12" },
    { label: "고객사 관리", href: "/?page=customers", active: false, count: "" },
    { label: "제출자료 검토", href: "/?page=review", active: false, count: "" },
    { label: "서비스 관리", href: "/?page=templates", active: false, count: "" },
    { label: "설정", href: "#", active: false, count: "" },
  ],
  summary: [
    {
      label: "검토 대기 자료",
      value: "18",
      helper: "신규 4건",
      hoverTitle: "신규 제출 고객사",
      customers: ["샘플테크 주식회사", "브릿지AI", "오르빗헬스", "루멘커머스"],
      tone: "primary",
      configurable: true,
    },
    {
      label: "자료 미제출 고객사",
      value: "5",
      alertDays: 5,
      dueCustomers: ["샘플테크 주식회사", "루멘커머스", "오르빗헬스", "메디코어랩", "노스브릿지"],
      tone: "warning",
      settingType: "due",
      configurable: true,
    },
    {
      label: "고객사 요청사항",
      value: "7",
      helper: "신규 3건",
      hoverTitle: "요청사항 입력 고객사",
      customers: ["루멘커머스", "메디코어랩", "노스브릿지"],
      tone: "danger",
      configurable: true,
    },
  ],
  notifications: [
    {
      type: "자료 접수",
      title: "샘플테크 주식회사",
      detail: "통장 입금 내역",
      time: "방금 전",
    },
    {
      type: "자료 접수",
      title: "브릿지AI",
      detail: "PG 정산자료",
      time: "3분 전",
    },
  ],
  queue: [
    {
      priority: "높음",
      company: "샘플테크 주식회사",
      request: "2025년 1기 부가가치세 신고 검토",
      document: "부가세 신고서",
      status: "검토 주의",
      deadline: "오늘 18:00",
      deadlineSort: "2026-05-19T18:00:00+09:00",
      receivedAt: "2026-05-19T14:20:00+09:00",
      owner: "김세무",
      reason: "필수 항목 일부의 인식 신뢰도가 낮아 원문 확인이 필요합니다.",
      evidence: "공급가액과 세액 영역 확인 필요",
      tone: "warning",
    },
    {
      priority: "높음",
      company: "루멘커머스",
      request: "월간 매출 정산자료 검토",
      document: "PG 정산자료",
      status: "검토 주의",
      deadline: "내일",
      deadlineSort: "2026-05-20T18:00:00+09:00",
      receivedAt: "2026-05-19T13:40:00+09:00",
      owner: "박회계",
      reason: "정산 기간은 맞지만 일부 수수료 항목의 인식률이 낮습니다.",
      evidence: "정산합계 시트 수수료 컬럼 OCR 신뢰도 낮음",
      tone: "warning",
    },
    {
      priority: "보통",
      company: "브릿지AI",
      request: "투자 실사 자료 준비",
      document: "주요 매출계약서",
      status: "검토 대기",
      deadline: "2026-05-23",
      deadlineSort: "2026-05-23T18:00:00+09:00",
      receivedAt: "2026-05-18T17:05:00+09:00",
      owner: "이주니어",
      reason: "계약 당사자, 계약일, 계약금액, 기간이 확인되었습니다.",
      evidence: "계약서 1페이지, 3페이지 금액 조항",
      tone: "success",
    },
    {
      priority: "보통",
      company: "샘플테크 주식회사",
      request: "2025년 1기 부가가치세 신고 검토",
      document: "매출 세금계산서 합계표",
      status: "검토 대기",
      deadline: "2026-05-27",
      deadlineSort: "2026-05-27T18:00:00+09:00",
      receivedAt: "2026-05-19T09:10:00+09:00",
      owner: "김세무",
      reason: "요청 문서와 필수 항목이 확인되어 원문 대조가 필요합니다.",
      evidence: "사업자등록번호, 과세기간, 공급가액 합계 확인",
      tone: "primary",
    },
    {
      priority: "낮음",
      company: "오르빗헬스",
      request: "법인세 기초자료 수집",
      document: "사업자등록증",
      status: "검토 대기",
      deadline: "2026-05-30",
      deadlineSort: "2026-05-30T18:00:00+09:00",
      receivedAt: "2026-05-17T10:30:00+09:00",
      owner: "정리뷰",
      reason: "요청 문서와 필수 식별값이 모두 확인되었습니다.",
      evidence: "사업자등록번호, 대표자명, 사업장 주소 확인",
      tone: "success",
    },
  ],
};
