export const accountantCustomerManagementContent = {
  summary: [
    { label: "전체 고객사", value: "42", helper: "활성 37개사" },
    { label: "등록 담당자", value: "86", helper: "평균 2.3명" },
    { label: "연락처 미완성", value: "6", helper: "보완 필요" },
  ],
  customers: [
    {
      id: "sample-tech",
      company: "샘플테크 주식회사",
      businessNumber: "123-45-67890",
      ceoName: "김샘플",
      businessType: "정보통신업",
      businessItem: "소프트웨어 개발 및 공급업",
      address: "서울특별시 강남구 테헤란로 123, 10층",
      memo: "부가세 신고와 투자 실사 요청이 반복되는 고객사입니다.",
      contacts: [
        {
          id: "sample-tech-contact-1",
          name: "최지훈",
          title: "CFO",
          phone: "010-1234-5678",
          email: "finance@sampletech.kr",
          primary: true,
        },
        {
          id: "sample-tech-contact-2",
          name: "한서윤",
          title: "재무팀 매니저",
          phone: "010-2222-7788",
          email: "accounting@sampletech.kr",
          primary: false,
        },
      ],
    },
    {
      id: "lumen-commerce",
      company: "루멘커머스",
      businessNumber: "234-56-78901",
      ceoName: "최루멘",
      businessType: "도소매업",
      businessItem: "전자상거래 소매업",
      address: "서울특별시 마포구 월드컵북로 45",
      memo: "플랫폼 정산자료와 PG 정산자료 요청이 잦습니다.",
      contacts: [
        {
          id: "lumen-commerce-contact-1",
          name: "이서연",
          title: "재무팀장",
          phone: "010-2345-6789",
          email: "accounting@lumencommerce.co.kr",
          primary: true,
        },
      ],
    },
    {
      id: "bridge-ai",
      company: "브릿지AI",
      businessNumber: "345-67-89012",
      ceoName: "박민수",
      businessType: "전문서비스업",
      businessItem: "AI 솔루션 개발 및 자문",
      address: "경기도 성남시 분당구 판교역로 235",
      memo: "투자 실사와 주주 관련 자료 요청 가능성이 높습니다.",
      contacts: [
        {
          id: "bridge-ai-contact-1",
          name: "박민수",
          title: "대표",
          phone: "010-3456-7890",
          email: "ceo@bridgeai.kr",
          primary: true,
        },
        {
          id: "bridge-ai-contact-2",
          name: "오유진",
          title: "운영 리드",
          phone: "010-3333-5577",
          email: "ops@bridgeai.kr",
          primary: false,
        },
      ],
    },
    {
      id: "orbit-health",
      company: "오르빗헬스",
      businessNumber: "456-78-90123",
      ceoName: "윤오르빗",
      businessType: "보건업",
      businessItem: "디지털 헬스케어 서비스",
      address: "서울특별시 송파구 올림픽로 300",
      memo: "법인세 기초자료 수집 완료 후 보관 상태입니다.",
      contacts: [
        {
          id: "orbit-health-contact-1",
          name: "정다은",
          title: "운영매니저",
          phone: "010-4567-8901",
          email: "ops@orbithealth.kr",
          primary: true,
        },
      ],
    },
  ],
};
