export const taxInvoiceQwenJudgment = {
  documentName: "매출 세금계산서",
  status: "approved",
  isExpectedDocument: true,
  confidencePercent: 98,
  summary: "원본 이미지와 OCR 보조 결과를 함께 확인한 결과, 세금계산서 양식과 필수 식별값이 확인되었습니다.",
  reason: "문서명, 공급자/공급받는자 정보, 작성일자, 품목, 공급가액, 세액, 합계금액이 원본 이미지에서 식별되었습니다.",
  evidence: "문서명: 세금계산서(공급자 보관용), 공급자 등록번호: 632-08-00201, 공급가액: 70,000, 세액: 7,000, 합계금액: 77,000",
  fields: [
    { label: "문서명/양식명", value: "세금계산서(공급자보관용)", confidence: "높음" },
    { label: "공급자 등록번호", value: "632-08-00201", confidence: "높음" },
    { label: "공급자 상호 또는 성명", value: "한경세무회계", confidence: "높음" },
    { label: "공급받는자 등록번호", value: "000-00-00000", confidence: "높음" },
    { label: "공급받는자 상호 또는 성명", value: "홍길동", confidence: "높음" },
    { label: "작성일자", value: "2020년 7월 24일", confidence: "높음" },
    { label: "품목 또는 거래내용", value: "기장료", confidence: "높음" },
    { label: "공급가액", value: "70,000", confidence: "높음" },
    { label: "세액", value: "7,000", confidence: "높음" },
    { label: "합계금액", value: "77,000", confidence: "높음" },
  ],
  reviewMemo: "Qwen3.6 멀티모달 판단 결과 필수 항목는 확인되었습니다. 최종 판단 전 원본 이미지와 금액을 직접 대조하세요.",
  sourceFile: "tmp/ocr-samples/a0e240d1567dd.png",
  requestedDocument: "매출 세금계산서",
  qwenModel: "Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf",
  imageInputUsed: true,
};

export const bankbookQwenJudgment = {
  documentName: "통장 사본",
  status: "review_required",
  isExpectedDocument: true,
  confidencePercent: 63,
  summary: "통장 사본 양식은 확인되지만, 계좌번호 영역이 훼손되어 필수값 일부를 원본에서 안정적으로 읽기 어렵습니다.",
  reason: "은행명, 예금주, 상품명, 개설일자는 확인되지만 계좌번호 영역은 OCR/Qwen 모두 재확인이 필요한 상태로 처리해야 합니다.",
  evidence: "문서 상단 계좌번호 행이 노이즈 처리되어 있어 계좌번호 필드의 자동 판독 신뢰도가 낮습니다.",
  fields: [
    {
      label: "문서명/양식명",
      value: "통장 사본",
      confidence: "높음",
      sourceRegion: { page: 1, x: 3.8, y: 26.5, width: 22, height: 8 },
    },
    {
      label: "은행명",
      value: "우리은행",
      confidence: "높음",
      sourceRegion: { page: 1, x: 3.8, y: 26.5, width: 22, height: 8 },
    },
    {
      label: "예금주",
      value: "홍길동",
      confidence: "높음",
      sourceRegion: { page: 1, x: 78.3, y: 12.9, width: 12, height: 5.3 },
    },
    {
      label: "계좌번호",
      value: "인식 불안정",
      confidence: "낮음",
      sourceRegion: { page: 1, x: 16.7, y: 16.6, width: 27.3, height: 5.3 },
    },
    {
      label: "예금종류 또는 상품명",
      value: "기업자유예금(우리CUBE통장)",
      confidence: "높음",
      sourceRegion: { page: 1, x: 15.7, y: 20.9, width: 36.1, height: 3.1 },
    },
    {
      label: "발행일자 또는 개설일자",
      value: "2019-11-27",
      confidence: "높음",
      sourceRegion: { page: 1, x: 24.3, y: 23.5, width: 25.5, height: 3 },
    },
    {
      label: "지점명",
      value: "서초구청지점",
      confidence: "높음",
      sourceRegion: { page: 1, x: 14.6, y: 40.9, width: 20, height: 3.5 },
    },
  ],
  reviewMemo: "계좌번호 영역이 훼손되어 자동 판독값을 그대로 쓰면 안 됩니다. 고객에게 선명한 통장 사본을 재요청하거나 원본으로 계좌번호를 직접 확인하세요.",
  sourceFile: "public/samples/bankbook-sample-low-confidence.png",
  requestedDocument: "통장 사본",
  qwenModel: "Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf",
  imageInputUsed: true,
};
