export const customerPortalContent = {
  brand: {
    eyebrow: "AuditMind",
    title: "자료 제출 포털",
    symbolText: "AM",
    symbolImage: "",
    symbolAlt: "AuditMind",
    badges: [],
  },
  request: {
    meta: "",
    title: "2025년 1기 부가가치세 신고 검토 자료 제출 요청",
    description: "",
    progressLabel: "자료 제출률",
    progressValue: "58%",
    progressDetail: "총 12개 자료 중 7개 접수 완료",
    deadlineLabel: "접수 마감일",
    deadlineValue: "2026년 5월 27일",
    deadlineDetail: "마감까지 9일 남았습니다.",
    deadlinePercent: "64%",
  },
  bulkUpload: {
    title: "자료 업로드",
    description: "",
    guidance: [
      "자료의 품질이 낮거나 누락 사항이 많은 경우 오류로 표시되거나 다시 제출요청을 받으실 수 있습니다.",
      "고객님의 개인 정보는 외부로 유출되지 않고 AuditMind 내부에서만 사용됩니다.",
    ],
    supportedLabel: "지원파일",
    supportedFiles: [
      "PDF",
      "XLS",
      "XLSX",
      "XLSM",
      "CSV",
      "TSV",
      "DOC",
      "DOCX",
      "HWP",
      "HWPX",
      "JPG",
      "JPEG",
      "PNG",
      "HEIC",
      "HEIF",
      "WEBP",
      "TIFF",
      "TIF",
      "ZIP",
    ],
    formats: [],
    button: "파일 다중 선택",
    overlayTitle: "파일 업로드 중",
    overlayDescriptionLines: [
      "선택한 파일을 안전하게 접수하고 있습니다.",
      "이 단계가 끝나면 분석은 백그라운드에서 계속 진행됩니다.",
    ],
    overlayComplete: "파일 분석 시작",
    overlayCompleteDescriptionLines: [
      "파일 업로드가 완료되었습니다.",
      "문서 분류와 분석은 이 페이지를 나가셔도 계속 진행됩니다.",
    ],
    overlayConfirm: "확인",
    overlayRetry: "다시 시도",
    overlayClose: "닫기",
    overlayFailureTitle: "파일 업로드 실패",
    overlayFailureDescriptionLines: [
      "파일 업로드에 실패했습니다.",
      "인터넷 연결을 확인한 뒤 다시 시도해 주세요.",
    ],
  },
  customerRequest: {
    title: "요청사항",
    helper: "제출 버튼을 누르셔야 요청사항이 접수됩니다.",
    placeholder: "",
    defaultValue: "",
    saveAction: "저장",
    editAction: "수정",
    submitAction: "제출",
    submittedAction: "제출",
  },
  checklist: {
    title: "자료 제출",
    description: "최종 접수 버튼을 누르기 전까지는 자료가 전달되지 않습니다. 반드시 최종 접수 버튼을 눌러주세요.",
    filters: ["전체", "미접수"],
    finalSubmitAction: "최종 접수",
    finalSubmitConfirmTitle: "이 자료를 최종 접수할까요?",
    finalSubmitConfirmDescription: "최종 접수하면 더 이상 수정할 수 없습니다.",
    finalSubmitCancel: "취소",
    items: [
      {
        status: "검수완료",
        statusTone: "success",
        title: "부가세 신고서",
        description: "홈택스에서 내려받은 2025년 1기 부가세 신고서 PDF입니다.",
        reviewMessage: "AI 검수 완료율 100%입니다. 제출 기준에 맞게 첨부되었습니다.",
        note: "부가세_신고서_2025_1기.pdf · 오늘 09:42 제출",
        attachment: {
          name: "부가세_신고서_2025_1기.pdf",
          submittedAt: "오늘 09:42 제출",
        },
        action: "파일 업로드",
      },
      {
        status: "오류",
        statusTone: "danger",
        highlight: true,
        title: "카드매출 내역",
        description: "카드사 또는 POS에서 받은 월별 카드매출 자료입니다.",
        reviewMessage: "오류 사유: 3월 자료가 빠진 것으로 보입니다. 1월, 2월 파일만 자동 매칭되었습니다.",
        accountantComment: "3월 카드매출 내역도 추가로 업로드해 주세요. 카드사 관리자 페이지에서 월별 매출자료로 내려받으시면 됩니다.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
      {
        status: "분석 중",
        statusTone: "processing",
        title: "매출 세금계산서 합계표",
        description: "거래처별 매출 세금계산서를 합산한 자료입니다.",
        reviewMessage: "AI가 문서를 분석 중입니다.",
        note: "",
        action: "파일 업로드",
      },
      {
        status: "미접수",
        statusTone: "neutral",
        title: "통장 입금 내역",
        description: "은행에서 내려받은 2025년 1분기 계좌 거래내역입니다. 엑셀 또는 PDF 모두 가능합니다.",
        reviewMessage: "아직 접수되지 않았습니다. 자료를 찾아 업로드해 주세요.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
      {
        status: "검수완료",
        statusTone: "success",
        title: "PG 정산자료",
        description: "토스페이먼츠, 나이스페이, 카카오페이 등 결제대행사 정산 내역입니다.",
        reviewMessage: "AI 검수 완료율 100%입니다. 제출 기준에 맞게 첨부되었습니다.",
        accountantComment: "확인되었습니다. 추가 제출은 필요하지 않습니다.",
        note: "PG_정산자료_2025_1기.zip · 어제 18:12 제출",
        attachment: {
          name: "PG_정산자료_2025_1기.zip",
          submittedAt: "어제 18:12 제출",
        },
        action: "파일 업로드",
      },
      {
        status: "미접수",
        statusTone: "neutral",
        title: "주요 매출계약서",
        description: "큰 거래처와 체결한 계약서입니다. PDF, 스캔 이미지, Word 파일 모두 가능합니다.",
        reviewMessage: "아직 접수되지 않았습니다. 자료를 찾아 업로드해 주세요.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
    ],
  },
  customerMessage: {
    label: "안내 메시지",
    manualMessage: "",
    useAiWhenEmpty: true,
    qwenEndpoint: "/api/qwen/chat/completions",
    qwenModel: "Qwen3.6-35B-A3B-NVFP4",
    qwenReasoning: false,
    validation: "rejectJapaneseOrChineseCharacters",
    preparingText: "AI가 검토 중입니다.",
    generatedMessage:
      "현재 **자료 제출률**과 **접수 마감일**을 기준으로 남은 자료를 안내합니다. 필요한 자료를 차근차근 업로드해 주세요.",
  },
  legalFooter: {
    companyName: "AuditMind 주식회사",
    representative: "홍길동",
    businessRegistrationNumber: "000-00-00000",
    mailOrderRegistrationNumber: "제2026-서울강남-00000호",
    address: "서울특별시 강남구 테헤란로 000, 00층",
    phone: "02-0000-0000",
    email: "populationinversion@gmail.com",
    privacyOfficer: "개인정보 보호책임자 privacy@auditmind.co.kr",
    links: ["개인정보처리방침", "이용약관", "보안 및 자료보호 안내", "사업자정보 확인"],
    copyright: "© 2026 AuditMind. All rights reserved.",
  },
  access: {
    expired: {
      title: "이 링크는 더 이상 사용할 수 없습니다.",
      description: "담당자에게 새 링크를 요청해 주세요.",
    },
    invalid: {
      title: "접근할 수 없는 제출 페이지입니다.",
      description: "링크가 올바른지 확인해 주세요.",
    },
  },
};
