export const customerPortalContent = {
  brand: {
    eyebrow: "AuditMind",
    title: "자료 제출 포털",
    symbolText: "AM",
    symbolImage: "",
    symbolAlt: "AuditMind",
    badges: ["샘플테크 주식회사"],
  },
  request: {
    meta: "",
    title: "2025년 1기 부가가치세 신고 검토 자료 제출 요청",
    description: "",
    progressLabel: "자료 제출률",
    progressValue: "58%",
    progressDetail: "총 12개 자료 중 7개 접수 완료",
    deadlineLabel: "접수 마감일",
    deadlineValue: "2026년 5월 27일",
    deadlineDetail: "마감까지 9일 남았습니다.",
    deadlinePercent: "64%",
  },
  bulkUpload: {
    title: "자료 업로드",
    description:
      "실행 파일, 암호가 걸린 압축 파일, 손상된 파일은 처리할 수 없습니다.",
    supportedLabel: "지원파일",
    supportedFiles: [
      "PDF",
      "XLS",
      "XLSX",
      "XLSM",
      "CSV",
      "TSV",
      "DOC",
      "DOCX",
      "HWP",
      "HWPX",
      "JPG",
      "JPEG",
      "PNG",
      "HEIC",
      "HEIF",
      "WEBP",
      "TIFF",
      "TIF",
      "ZIP",
      "7Z",
    ],
    formats: [],
    button: "파일 선택",
    overlayTitle: "파일 업로드 중",
    overlayDescriptionLines: [
      "선택한 파일을 안전하게 접수하고 있습니다.",
      "이 단계가 끝나면 분석은 백그라운드에서 계속 진행됩니다.",
    ],
    overlayComplete: "파일 분석 시작",
    overlayCompleteDescriptionLines: [
      "파일 업로드가 완료되었습니다.",
      "문서 분류와 분석은 이 페이지를 나가셔도 계속 진행됩니다.",
    ],
    overlayConfirm: "확인",
  },
  checklist: {
    title: "자료 제출",
    description: "최종 접수 버튼을 누르기 전까지는 자료가 전달되지 않습니다. 반드시 최종 접수 버튼을 눌러주세요.",
    filters: ["전체", "미접수"],
    finalSubmitAction: "최종 접수",
    items: [
      {
        status: "검수완료",
        statusTone: "success",
        title: "부가세 신고서",
        description: "홈택스에서 내려받은 2025년 1기 부가세 신고서 PDF입니다.",
        reviewMessage: "AI 검수 완료율 100%입니다. 제출 기준에 맞게 첨부되었습니다.",
        note: "부가세_신고서_2025_1기.pdf · 오늘 09:42 제출",
        attachment: {
          name: "부가세_신고서_2025_1기.pdf",
          submittedAt: "오늘 09:42 제출",
        },
        action: "파일 업로드",
      },
      {
        status: "반려",
        statusTone: "danger",
        highlight: true,
        title: "카드매출 내역",
        description: "카드사 또는 POS에서 받은 월별 카드매출 자료입니다.",
        reviewMessage: "반려 사유: 3월 자료가 빠진 것으로 보입니다. 1월, 2월 파일만 자동 매칭되었습니다.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
      {
        status: "분석 중",
        statusTone: "processing",
        title: "매출 세금계산서 합계표",
        description: "거래처별 매출 세금계산서를 합산한 자료입니다.",
        reviewMessage: "AI가 문서를 분석 중입니다. 잠시 후 검수 완료율과 결과가 표시됩니다.",
        note: "",
        action: "파일 업로드",
      },
      {
        status: "미접수",
        statusTone: "neutral",
        title: "통장 입금 내역",
        description: "은행에서 내려받은 2025년 1분기 계좌 거래내역입니다. 엑셀 또는 PDF 모두 가능합니다.",
        reviewMessage: "아직 접수되지 않았습니다. 자료를 찾아 업로드해 주세요.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
      {
        status: "검수완료",
        statusTone: "success",
        title: "PG 정산자료",
        description: "토스페이먼츠, 나이스페이, 카카오페이 등 결제대행사 정산 내역입니다.",
        reviewMessage: "AI 검수 완료율 100%입니다. 제출 기준에 맞게 첨부되었습니다.",
        note: "PG_정산자료_2025_1기.zip · 어제 18:12 제출",
        attachment: {
          name: "PG_정산자료_2025_1기.zip",
          submittedAt: "어제 18:12 제출",
        },
        action: "파일 업로드",
      },
      {
        status: "미접수",
        statusTone: "neutral",
        title: "주요 매출계약서",
        description: "큰 거래처와 체결한 계약서입니다. PDF, 스캔 이미지, Word 파일 모두 가능합니다.",
        reviewMessage: "아직 접수되지 않았습니다. 자료를 찾아 업로드해 주세요.",
        note: "",
        action: "파일 업로드",
        primaryAction: true,
      },
    ],
  },
  customerMessage: {
    label: "안내 메시지",
    manualMessage: "",
    useAiWhenEmpty: true,
    qwenEndpoint: "/api/qwen/chat/completions",
    qwenModel: "Qwen3.6-35B-A3B-NVFP4",
    qwenReasoning: false,
    validation: "rejectJapaneseOrChineseCharacters",
    preparingText: "메시지를 준비하고 있습니다.",
    generatedMessage:
      "샘플테크 주식회사 담당자님, 현재 **자료 제출률은 58%**이며 **접수 마감일은 2026년 5월 27일**입니다. 아직 미접수된 자료가 있어 확인이 필요하지만, 지금처럼 차근차근 올려주시면 더 빠르고 정확한 검토가 가능합니다. 바쁜 일정 속에서도 여기까지 준비해 주신 것만으로도 충분히 잘 진행되고 있습니다. 남은 자료도 편하실 때 이어서 제출해 주세요.",
  },
  sidebar: {
    nextTitle: "참고 사항",
    firmName: "AuditMind",
    nextSteps: [
      "최종 접수하기 전까지 언제든지 자료를 다시 업로드하실 수 있습니다.",
      "자료의 품질이 낮거나 누락 사항이 많은 경우 제출이 반려되거나 다시 제출요청을 받으실 수 있습니다.",
      "고객님의 개인 정보는 외부로 유출되지 않고 ##### 내부에서만 사용됩니다.",
    ],
  },
};
